# Default values for helm-guestbook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ylorenzati/mygoapp
  tag: latest
  pullPolicy: IfNotPresent

nodeSelector: {}

tolerations: []

affinity: {}
